### ISSUE TITLE
new Aliexpress Requirements 

### ISSUE THREAD

**Issue by Snir10** [sergioteula/python-aliexpress-api#24]
Traceback (most recent call last):
  File "C:\Users\Home\PycharmProjects\python\telegram-import-from-group\telegram-importer.py", line 431, in <module>
    client.loop.run_until_complete(main())
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Home\PycharmProjects\python\telegram-import-from-group\telegram-importer.py", line 352, in main
    resp = setAffiliateLink(next_url, no_link_received_cnt, aliexpress)
  File "C:\Users\Home\PycharmProjects\python\telegram-import-from-group\telegram-importer.py", line 117, in setAffiliateLink
    resp = aliexpress.get_affiliate_links(next_url)
  File "C:\Users\Home\PycharmProjects\python\venv\lib\site-packages\aliexpress_api\api.py", line 124, in get_affiliate_links
    response = api_request(request, 'aliexpress_affiliate_link_generate_response')
  File "C:\Users\Home\PycharmProjects\python\venv\lib\site-packages\aliexpress_api\helpers\requests.py", line 12, in api_request
    raise ApiRequestException(error.message) from error
**aliexpress_api.errors.exceptions.ApiRequestException: Platform System blacklist:aobao Open Platform (TOP) has been offline. Please view details at &quot;https://open.aliexpress.com/doc/doc.htm#/?docId=1236&quot; and migrate to the new open platform.**

Process finished with exit code 1

can we do something on code? do you have estimate fix for it?

**Comment by Snir10** [comment]
resp = aliexpress.get_affiliate_links(next_url)

**Comment by Snir10** [comment]
@sergioteula any update please?

**Comment by Snir10** [comment]
please any update?
